@url = https://fluffy-train-q7v7r5wvqpp7h6wrg-3000.app.github.dev

GET {{url}}/api/v1/generos

###
POST {{url}}/api/v1/generos
Content-Type: application/json

{
    "id" : 10,
    "nome" : "Biografia"
}